[env]
term = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.9

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
# normal = { family = "Maple Mono", style = "Regular" }
# offset = { x = 0, y = 0 }
size = 15

[colors]
cursor = { text = "#000000", cursor = "#38ff9c" }

[colors.primary]
foreground = "#ebddf4"
background = "#010b17"

[colors.normal]
black = "#0b3b61"
red = "#ff3a3a"
green = "#52ffcf"
yellow = "#fff383"
blue = "#1376f8"
magenta = "#c792ea"
cyan = "#7FFFD4"
white = "#15fca2"

[cursor]
vi_mode_style = { shape = "Beam" }
