# [[manager.prepend_keymap]]
# on   = "l"
# run  = "plugin --- @sync entry smart-enter"
# desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "u"
run = "tab_switch --relative 1"
desc = "Next Tab"

[[manager.prepend_keymap]]
on = "i"
run = "tab_switch --relative -1"
desc = "Previous Tab"

[[manager.prepend_keymap]]
on   = "t"
run  = "plugin --@sync smart-tab"
desc = "Create a tab and enter the hovered directory"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin --@sync hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on = [ "<C-n>" ]
run = '''shell 'dragon-drop -x -i -T "$1"' --confirm'''

[[manager.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions --args=1"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions --args=2"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions --args=3"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions --args=4"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions --args=5"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions --args=6"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions --args=7"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions --args=8"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions --args=9"
desc = "Move in relative steps"
